// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package unbound_method

import "github.com/go-json-experiment/json"

type UnboundMethodOptions struct {
	// IgnoreStatic corresponds to the JSON schema field "ignoreStatic".
	IgnoreStatic bool `json:"ignoreStatic,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UnboundMethodOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain UnboundMethodOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["ignoreStatic"]; !ok || v == nil {
		plain.IgnoreStatic = false
	}
	*j = UnboundMethodOptions(plain)
	return nil
}
