// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package consistent_type_exports

import "github.com/go-json-experiment/json"

type ConsistentTypeExportsOptions struct {
	// FixMixedExportsWithInlineTypeSpecifier corresponds to the JSON schema field
	// "fixMixedExportsWithInlineTypeSpecifier".
	FixMixedExportsWithInlineTypeSpecifier bool `json:"fixMixedExportsWithInlineTypeSpecifier,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConsistentTypeExportsOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ConsistentTypeExportsOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["fixMixedExportsWithInlineTypeSpecifier"]; !ok || v == nil {
		plain.FixMixedExportsWithInlineTypeSpecifier = false
	}
	*j = ConsistentTypeExportsOptions(plain)
	return nil
}
