// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_unsafe_member_access

import "github.com/go-json-experiment/json"

type NoUnsafeMemberAccessOptions struct {
	// Whether to allow `?.` optional chains on `any` values.
	AllowOptionalChaining bool `json:"allowOptionalChaining,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoUnsafeMemberAccessOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoUnsafeMemberAccessOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowOptionalChaining"]; !ok || v == nil {
		plain.AllowOptionalChaining = false
	}
	*j = NoUnsafeMemberAccessOptions(plain)
	return nil
}
