packages:
  - packages/effect-vitest
  - packages/oxlint-effect
  - packages/tsgolint-effect
  - packages/vite-plus

catalog:
  {
    "@types/node": ^24.7.2,
    effect: 4.0.0-beta.93,
    tsx: npm:tsx@4.22.3,
    vite: npm:@voidzero-dev/vite-plus-core@0.2.2,
    vite-plus: 0.2.2,
  }

allowBuilds:
  esbuild: true
  msgpackr-extract: true
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
minimumReleaseAgeExclude:
  - '@tiara-stack/tsgolint-effect@0.1.0'
