packages:
  - packages/effect-vitest
  - packages/oxlint-effect
  - packages/oxlint-effect-linux-x64
  - packages/tsgo-effect
  - packages/tsgo-effect-linux-x64
  - packages/tsgolint-effect
  - packages/tsgolint-effect-linux-x64
  - packages/vite-plus

catalog:
  {
    "@types/node": ^24.7.2,
    effect: 4.0.0-beta.93,
    tsx: npm:tsx@4.22.3,
    vite: npm:@voidzero-dev/vite-plus-core@0.2.2,
    vite-plus: 0.2.2,
  }

allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false
  msgpackr-extract: true
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
minimumReleaseAgeExclude:
  - '@tiara-stack/oxlint-effect-linux-x64@0.1.0'
  - '@tiara-stack/tsgo-effect@0.1.0'
  - '@tiara-stack/tsgo-effect-linux-x64@0.1.0'
  - '@tiara-stack/tsgolint-effect@0.1.0'
  - '@tiara-stack/tsgolint-effect-linux-x64@0.1.0'
  - '@tiara-stack/vite-plus@0.2.2'
  - '@tiara-stack/vite-plus@0.2.3'
