// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package restrict_template_expressions

import "github.com/go-json-experiment/json"
import "github.com/effect-ts/tsgo/tsgolint/internal/utils"

type RestrictTemplateExpressionsOptions struct {
	// Allow corresponds to the JSON schema field "allow".
	Allow []utils.TypeOrValueSpecifier `json:"allow"`

	// AllowAny corresponds to the JSON schema field "allowAny".
	AllowAny bool `json:"allowAny,omitempty"`

	// AllowArray corresponds to the JSON schema field "allowArray".
	AllowArray bool `json:"allowArray,omitempty"`

	// AllowBoolean corresponds to the JSON schema field "allowBoolean".
	AllowBoolean bool `json:"allowBoolean,omitempty"`

	// AllowNever corresponds to the JSON schema field "allowNever".
	AllowNever bool `json:"allowNever,omitempty"`

	// AllowNullish corresponds to the JSON schema field "allowNullish".
	AllowNullish bool `json:"allowNullish,omitempty"`

	// AllowNumber corresponds to the JSON schema field "allowNumber".
	AllowNumber bool `json:"allowNumber,omitempty"`

	// AllowRegExp corresponds to the JSON schema field "allowRegExp".
	AllowRegExp bool `json:"allowRegExp,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RestrictTemplateExpressionsOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain RestrictTemplateExpressionsOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow"]; !ok || v == nil {
		plain.Allow = []utils.TypeOrValueSpecifier{
			{
				From: utils.TypeOrValueSpecifierFromLib,
				Name: []string{"Error", "URL", "URLSearchParams"},
			},
		}
	}
	if v, ok := raw["allowAny"]; !ok || v == nil {
		plain.AllowAny = true
	}
	if v, ok := raw["allowArray"]; !ok || v == nil {
		plain.AllowArray = false
	}
	if v, ok := raw["allowBoolean"]; !ok || v == nil {
		plain.AllowBoolean = true
	}
	if v, ok := raw["allowNever"]; !ok || v == nil {
		plain.AllowNever = false
	}
	if v, ok := raw["allowNullish"]; !ok || v == nil {
		plain.AllowNullish = true
	}
	if v, ok := raw["allowNumber"]; !ok || v == nil {
		plain.AllowNumber = true
	}
	if v, ok := raw["allowRegExp"]; !ok || v == nil {
		plain.AllowRegExp = true
	}
	*j = RestrictTemplateExpressionsOptions(plain)
	return nil
}
