// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package consistent_return

import "github.com/go-json-experiment/json"

type ConsistentReturnOptions struct {
	// TreatUndefinedAsUnspecified corresponds to the JSON schema field
	// "treatUndefinedAsUnspecified".
	TreatUndefinedAsUnspecified bool `json:"treatUndefinedAsUnspecified,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConsistentReturnOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ConsistentReturnOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["treatUndefinedAsUnspecified"]; !ok || v == nil {
		plain.TreatUndefinedAsUnspecified = false
	}
	*j = ConsistentReturnOptions(plain)
	return nil
}
