// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_unnecessary_boolean_literal_compare

import "github.com/go-json-experiment/json"

type NoUnnecessaryBooleanLiteralCompareOptions struct {
	// AllowComparingNullableBooleansToFalse corresponds to the JSON schema field
	// "allowComparingNullableBooleansToFalse".
	AllowComparingNullableBooleansToFalse bool `json:"allowComparingNullableBooleansToFalse,omitempty"`

	// AllowComparingNullableBooleansToTrue corresponds to the JSON schema field
	// "allowComparingNullableBooleansToTrue".
	AllowComparingNullableBooleansToTrue bool `json:"allowComparingNullableBooleansToTrue,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoUnnecessaryBooleanLiteralCompareOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoUnnecessaryBooleanLiteralCompareOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowComparingNullableBooleansToFalse"]; !ok || v == nil {
		plain.AllowComparingNullableBooleansToFalse = true
	}
	if v, ok := raw["allowComparingNullableBooleansToTrue"]; !ok || v == nil {
		plain.AllowComparingNullableBooleansToTrue = true
	}
	*j = NoUnnecessaryBooleanLiteralCompareOptions(plain)
	return nil
}
