// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_confusing_void_expression

import "github.com/go-json-experiment/json"

type NoConfusingVoidExpressionOptions struct {
	// IgnoreArrowShorthand corresponds to the JSON schema field
	// "ignoreArrowShorthand".
	IgnoreArrowShorthand bool `json:"ignoreArrowShorthand,omitempty"`

	// IgnoreVoidOperator corresponds to the JSON schema field "ignoreVoidOperator".
	IgnoreVoidOperator bool `json:"ignoreVoidOperator,omitempty"`

	// IgnoreVoidReturningFunctions corresponds to the JSON schema field
	// "ignoreVoidReturningFunctions".
	IgnoreVoidReturningFunctions bool `json:"ignoreVoidReturningFunctions,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoConfusingVoidExpressionOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoConfusingVoidExpressionOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["ignoreArrowShorthand"]; !ok || v == nil {
		plain.IgnoreArrowShorthand = false
	}
	if v, ok := raw["ignoreVoidOperator"]; !ok || v == nil {
		plain.IgnoreVoidOperator = false
	}
	if v, ok := raw["ignoreVoidReturningFunctions"]; !ok || v == nil {
		plain.IgnoreVoidReturningFunctions = false
	}
	*j = NoConfusingVoidExpressionOptions(plain)
	return nil
}
