// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_duplicate_type_constituents

import "github.com/go-json-experiment/json"

type NoDuplicateTypeConstituentsOptions struct {
	// IgnoreIntersections corresponds to the JSON schema field "ignoreIntersections".
	IgnoreIntersections bool `json:"ignoreIntersections,omitempty"`

	// IgnoreUnions corresponds to the JSON schema field "ignoreUnions".
	IgnoreUnions bool `json:"ignoreUnions,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoDuplicateTypeConstituentsOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoDuplicateTypeConstituentsOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["ignoreIntersections"]; !ok || v == nil {
		plain.IgnoreIntersections = false
	}
	if v, ok := raw["ignoreUnions"]; !ok || v == nil {
		plain.IgnoreUnions = false
	}
	*j = NoDuplicateTypeConstituentsOptions(plain)
	return nil
}
