// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package restrict_plus_operands

import "github.com/go-json-experiment/json"

type RestrictPlusOperandsOptions struct {
	// Whether to allow `any` typed values
	AllowAny bool `json:"allowAny,omitempty"`

	// Whether to allow `boolean` typed values
	AllowBoolean bool `json:"allowBoolean,omitempty"`

	// Whether to allow potentially `null` or `undefined` typed values
	AllowNullish bool `json:"allowNullish,omitempty"`

	// Whether to allow mixing `number` and `string` typed values
	AllowNumberAndString bool `json:"allowNumberAndString,omitempty"`

	// Whether to allow `regexp` typed values
	AllowRegExp bool `json:"allowRegExp,omitempty"`

	// Whether to skip compound assignments such as `+=`
	SkipCompoundAssignments bool `json:"skipCompoundAssignments,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RestrictPlusOperandsOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain RestrictPlusOperandsOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowAny"]; !ok || v == nil {
		plain.AllowAny = true
	}
	if v, ok := raw["allowBoolean"]; !ok || v == nil {
		plain.AllowBoolean = true
	}
	if v, ok := raw["allowNullish"]; !ok || v == nil {
		plain.AllowNullish = true
	}
	if v, ok := raw["allowNumberAndString"]; !ok || v == nil {
		plain.AllowNumberAndString = true
	}
	if v, ok := raw["allowRegExp"]; !ok || v == nil {
		plain.AllowRegExp = true
	}
	if v, ok := raw["skipCompoundAssignments"]; !ok || v == nil {
		plain.SkipCompoundAssignments = false
	}
	*j = RestrictPlusOperandsOptions(plain)
	return nil
}
