// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package strict_boolean_expressions

import "github.com/go-json-experiment/json"

type StrictBooleanExpressionsOptions struct {
	// AllowAny corresponds to the JSON schema field "allowAny".
	AllowAny bool `json:"allowAny,omitempty"`

	// AllowNullableBoolean corresponds to the JSON schema field
	// "allowNullableBoolean".
	AllowNullableBoolean bool `json:"allowNullableBoolean,omitempty"`

	// AllowNullableEnum corresponds to the JSON schema field "allowNullableEnum".
	AllowNullableEnum bool `json:"allowNullableEnum,omitempty"`

	// AllowNullableNumber corresponds to the JSON schema field "allowNullableNumber".
	AllowNullableNumber bool `json:"allowNullableNumber,omitempty"`

	// AllowNullableObject corresponds to the JSON schema field "allowNullableObject".
	AllowNullableObject bool `json:"allowNullableObject,omitempty"`

	// AllowNullableString corresponds to the JSON schema field "allowNullableString".
	AllowNullableString bool `json:"allowNullableString,omitempty"`

	// AllowNumber corresponds to the JSON schema field "allowNumber".
	AllowNumber bool `json:"allowNumber,omitempty"`

	// AllowString corresponds to the JSON schema field "allowString".
	AllowString bool `json:"allowString,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StrictBooleanExpressionsOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain StrictBooleanExpressionsOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowAny"]; !ok || v == nil {
		plain.AllowAny = false
	}
	if v, ok := raw["allowNullableBoolean"]; !ok || v == nil {
		plain.AllowNullableBoolean = false
	}
	if v, ok := raw["allowNullableEnum"]; !ok || v == nil {
		plain.AllowNullableEnum = false
	}
	if v, ok := raw["allowNullableNumber"]; !ok || v == nil {
		plain.AllowNullableNumber = false
	}
	if v, ok := raw["allowNullableObject"]; !ok || v == nil {
		plain.AllowNullableObject = true
	}
	if v, ok := raw["allowNullableString"]; !ok || v == nil {
		plain.AllowNullableString = false
	}
	if v, ok := raw["allowNumber"]; !ok || v == nil {
		plain.AllowNumber = true
	}
	if v, ok := raw["allowString"]; !ok || v == nil {
		plain.AllowString = true
	}
	*j = StrictBooleanExpressionsOptions(plain)
	return nil
}
