// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_unnecessary_condition

import "github.com/go-json-experiment/json"

type NoUnnecessaryConditionOptions struct {
	// Whether to allow constant loop conditions. true is treated as "always", false
	// as "never".
	AllowConstantLoopConditions interface{} `json:"allowConstantLoopConditions,omitempty"`

	// Whether to check type predicate functions.
	CheckTypePredicates bool `json:"checkTypePredicates,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoUnnecessaryConditionOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoUnnecessaryConditionOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowConstantLoopConditions"]; !ok || v == nil {
		plain.AllowConstantLoopConditions = "never"
	}
	if v, ok := raw["checkTypePredicates"]; !ok || v == nil {
		plain.CheckTypePredicates = false
	}
	*j = NoUnnecessaryConditionOptions(plain)
	return nil
}
