name: Save dprint plugin cache

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dprint.json"
      - ".github/workflows/dprint.yml"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: taiki-e/install-action@682e7d9e49c5e653d371fc6adbda67653461378a # v2.82.4
        with:
          tool: dprint

      - run: dprint check

      - name: Save dprint plugin cache
        uses: actions/cache/save@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          key: dprint-${{ hashFiles('dprint.json') }}
          path: ~/.cache/dprint
