name: Update typescript-go

permissions: {}

on:
  push:
    branches:
      - renovate/typescript-go-*
    paths:
      - typescript-go

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # required for git am --3way to work properly
          submodules: true
          persist-credentials: true
          # Using secrets.GITHUB_TOKEN isn't allowed to trigger downstream
          # workflow runs, so we're using a Personal Access Token (PAT) instead
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Set committer identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

      - shell: bash
        run: |
          mkdir -p internal/collections
          find ./typescript-go/internal/collections -type f ! -name '*_test.go' -exec cp {} internal/collections/ \;

      - run: ./tools/update-typescript-go-shims.sh

      - name: Check for changes
        id: check_changes
        run: |
          if ! git diff --staged --quiet; then
            echo 'has_changes=true' >> "$GITHUB_OUTPUT"
          fi

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -m "update typescript-go"
          git push
