// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package require_array_sort_compare

import "github.com/go-json-experiment/json"

type RequireArraySortCompareOptions struct {
	// IgnoreStringArrays corresponds to the JSON schema field "ignoreStringArrays".
	IgnoreStringArrays bool `json:"ignoreStringArrays,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RequireArraySortCompareOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain RequireArraySortCompareOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["ignoreStringArrays"]; !ok || v == nil {
		plain.IgnoreStringArrays = true
	}
	*j = RequireArraySortCompareOptions(plain)
	return nil
}
