// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package strict_void_return

import "github.com/go-json-experiment/json"

type StrictVoidReturnOptions struct {
	// AllowReturnAny corresponds to the JSON schema field "allowReturnAny".
	AllowReturnAny bool `json:"allowReturnAny,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StrictVoidReturnOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain StrictVoidReturnOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowReturnAny"]; !ok || v == nil {
		plain.AllowReturnAny = false
	}
	*j = StrictVoidReturnOptions(plain)
	return nil
}
