// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package return_await

import "github.com/go-json-experiment/json"
import "fmt"
import "reflect"

type ReturnAwaitOptions string

const ReturnAwaitOptionsAlways ReturnAwaitOptions = "always"
const ReturnAwaitOptionsErrorHandlingCorrectnessOnly ReturnAwaitOptions = "error-handling-correctness-only"
const ReturnAwaitOptionsInTryCatch ReturnAwaitOptions = "in-try-catch"
const ReturnAwaitOptionsNever ReturnAwaitOptions = "never"

var enumValues_ReturnAwaitOptions = []interface{}{
	"always",
	"error-handling-correctness-only",
	"in-try-catch",
	"never",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReturnAwaitOptions) UnmarshalJSON(value []byte) error {
	// Handle null value by setting default (schema specifies "in-try-catch" as default)
	if string(value) == "null" {
		*j = ReturnAwaitOptionsInTryCatch
		return nil
	}

	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ReturnAwaitOptions {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ReturnAwaitOptions, v)
	}
	*j = ReturnAwaitOptions(v)
	return nil
}
