// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_readonly_parameter_types

import "github.com/go-json-experiment/json"
import "github.com/effect-ts/tsgo/tsgolint/internal/utils"

type PreferReadonlyParameterTypesOptions struct {
	// An array of type specifiers to ignore.
	Allow []utils.TypeOrValueSpecifier `json:"allow,omitempty"`

	// Whether to check class parameter properties.
	CheckParameterProperties bool `json:"checkParameterProperties,omitempty"`

	// Whether to ignore parameters which don't explicitly specify a type.
	IgnoreInferredTypes bool `json:"ignoreInferredTypes,omitempty"`

	// Whether to treat all mutable methods as though they are readonly.
	TreatMethodsAsReadonly bool `json:"treatMethodsAsReadonly,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferReadonlyParameterTypesOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferReadonlyParameterTypesOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow"]; !ok || v == nil {
		plain.Allow = []utils.TypeOrValueSpecifier{}
	}
	if v, ok := raw["checkParameterProperties"]; !ok || v == nil {
		plain.CheckParameterProperties = true
	}
	if v, ok := raw["ignoreInferredTypes"]; !ok || v == nil {
		plain.IgnoreInferredTypes = false
	}
	if v, ok := raw["treatMethodsAsReadonly"]; !ok || v == nil {
		plain.TreatMethodsAsReadonly = false
	}
	*j = PreferReadonlyParameterTypesOptions(plain)
	return nil
}
