// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package dot_notation

import "github.com/go-json-experiment/json"

type DotNotationOptions struct {
	// Whether to allow accessing properties matching an index signature with array
	// notation.
	AllowIndexSignaturePropertyAccess bool `json:"allowIndexSignaturePropertyAccess,omitempty"`

	// Whether to allow keywords such as ["class"].
	AllowKeywords bool `json:"allowKeywords,omitempty"`

	// Regular expression of names to allow.
	AllowPattern string `json:"allowPattern,omitempty"`

	// Whether to allow accessing class members marked as `private` with array
	// notation.
	AllowPrivateClassPropertyAccess bool `json:"allowPrivateClassPropertyAccess,omitempty"`

	// Whether to allow accessing class members marked as `protected` with array
	// notation.
	AllowProtectedClassPropertyAccess bool `json:"allowProtectedClassPropertyAccess,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DotNotationOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain DotNotationOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowIndexSignaturePropertyAccess"]; !ok || v == nil {
		plain.AllowIndexSignaturePropertyAccess = false
	}
	if v, ok := raw["allowKeywords"]; !ok || v == nil {
		plain.AllowKeywords = true
	}
	if v, ok := raw["allowPattern"]; !ok || v == nil {
		plain.AllowPattern = ""
	}
	if v, ok := raw["allowPrivateClassPropertyAccess"]; !ok || v == nil {
		plain.AllowPrivateClassPropertyAccess = false
	}
	if v, ok := raw["allowProtectedClassPropertyAccess"]; !ok || v == nil {
		plain.AllowProtectedClassPropertyAccess = false
	}
	*j = DotNotationOptions(plain)
	return nil
}
