// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_meaningless_void_operator

import "github.com/go-json-experiment/json"

type NoMeaninglessVoidOperatorOptions struct {
	// CheckNever corresponds to the JSON schema field "checkNever".
	CheckNever bool `json:"checkNever,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoMeaninglessVoidOperatorOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoMeaninglessVoidOperatorOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["checkNever"]; !ok || v == nil {
		plain.CheckNever = false
	}
	*j = NoMeaninglessVoidOperatorOptions(plain)
	return nil
}
