// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_deprecated

import "github.com/go-json-experiment/json"
import "github.com/effect-ts/tsgo/tsgolint/internal/utils"

type NoDeprecatedOptions struct {
	// Allow corresponds to the JSON schema field "allow".
	Allow []utils.TypeOrValueSpecifier `json:"allow,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoDeprecatedOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoDeprecatedOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow"]; !ok || v == nil {
		plain.Allow = []utils.TypeOrValueSpecifier{}
	}
	*j = NoDeprecatedOptions(plain)
	return nil
}
