name: Setup

description: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod

    - uses: extractions/setup-crate@7577c1bdf2d95e6d65d532788f35ed79d4b1dda2 # v2.0.1
      with:
        repo: casey/just
        version: ${{ inputs.just-version }}
        github-token: ${{ inputs.github-token }}

    - name: Set committer identity
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"

    - name: Apply typescript-go patches
      shell: bash
      run: |
        pushd typescript-go
        git am --3way --no-gpg-sign ../patches/*.patch
        popd

    - name: Expose typescript-go collections package
      shell: bash
      run: |
        mkdir -p internal/collections
        find ./typescript-go/internal/collections -type f ! -name '*_test.go' -exec cp {} internal/collections/ \;
