// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package promise_function_async

import "github.com/go-json-experiment/json"

type PromiseFunctionAsyncOptions struct {
	// AllowAny corresponds to the JSON schema field "allowAny".
	AllowAny bool `json:"allowAny,omitempty"`

	// AllowedPromiseNames corresponds to the JSON schema field "allowedPromiseNames".
	AllowedPromiseNames []string `json:"allowedPromiseNames,omitempty"`

	// CheckArrowFunctions corresponds to the JSON schema field "checkArrowFunctions".
	CheckArrowFunctions bool `json:"checkArrowFunctions,omitempty"`

	// CheckFunctionDeclarations corresponds to the JSON schema field
	// "checkFunctionDeclarations".
	CheckFunctionDeclarations bool `json:"checkFunctionDeclarations,omitempty"`

	// CheckFunctionExpressions corresponds to the JSON schema field
	// "checkFunctionExpressions".
	CheckFunctionExpressions bool `json:"checkFunctionExpressions,omitempty"`

	// CheckMethodDeclarations corresponds to the JSON schema field
	// "checkMethodDeclarations".
	CheckMethodDeclarations bool `json:"checkMethodDeclarations,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PromiseFunctionAsyncOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PromiseFunctionAsyncOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowAny"]; !ok || v == nil {
		plain.AllowAny = true
	}
	if v, ok := raw["allowedPromiseNames"]; !ok || v == nil {
		plain.AllowedPromiseNames = []string{}
	}
	if v, ok := raw["checkArrowFunctions"]; !ok || v == nil {
		plain.CheckArrowFunctions = true
	}
	if v, ok := raw["checkFunctionDeclarations"]; !ok || v == nil {
		plain.CheckFunctionDeclarations = true
	}
	if v, ok := raw["checkFunctionExpressions"]; !ok || v == nil {
		plain.CheckFunctionExpressions = true
	}
	if v, ok := raw["checkMethodDeclarations"]; !ok || v == nil {
		plain.CheckMethodDeclarations = true
	}
	*j = PromiseFunctionAsyncOptions(plain)
	return nil
}
